import type { EquipmentType } from '@/db/types';

export interface ExerciseTemplate {
  name: string;
  equipmentType: EquipmentType;
  category: string;
  defaultWeight: number;
  defaultSets: number;
  defaultRepsMin: number;
  defaultRepsMax: number;
  defaultProgressionIncrement: number;
}

export interface ExerciseCategory {
  name: string;
  exercises: ExerciseTemplate[];
}

export const EXERCISE_LIBRARY: ExerciseCategory[] = [
  {
    name: 'Chest',
    exercises: [
      {
        name: 'Bench Press',
        equipmentType: 'plates',
        category: 'Chest',
        defaultWeight: 60,
        defaultSets: 3,
        defaultRepsMin: 6,
        defaultRepsMax: 8,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Incline Bench Press',
        equipmentType: 'plates',
        category: 'Chest',
        defaultWeight: 50,
        defaultSets: 3,
        defaultRepsMin: 6,
        defaultRepsMax: 8,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Dumbbell Bench Press',
        equipmentType: 'other',
        category: 'Chest',
        defaultWeight: 20,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2,
      },
      {
        name: 'Incline Dumbbell Press',
        equipmentType: 'other',
        category: 'Chest',
        defaultWeight: 16,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2,
      },
      {
        name: 'Cable Fly',
        equipmentType: 'machine',
        category: 'Chest',
        defaultWeight: 10,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Chest Press Machine',
        equipmentType: 'machine',
        category: 'Chest',
        defaultWeight: 40,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 5,
      },
      {
        name: 'Dips',
        equipmentType: 'other',
        category: 'Chest',
        defaultWeight: 0,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Push-ups',
        equipmentType: 'other',
        category: 'Chest',
        defaultWeight: 0,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 0,
      },
    ],
  },
  {
    name: 'Back',
    exercises: [
      {
        name: 'Deadlift',
        equipmentType: 'plates',
        category: 'Back',
        defaultWeight: 80,
        defaultSets: 3,
        defaultRepsMin: 5,
        defaultRepsMax: 6,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Barbell Row',
        equipmentType: 'plates',
        category: 'Back',
        defaultWeight: 50,
        defaultSets: 3,
        defaultRepsMin: 6,
        defaultRepsMax: 8,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Lat Pulldown',
        equipmentType: 'machine',
        category: 'Back',
        defaultWeight: 50,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Seated Cable Row',
        equipmentType: 'machine',
        category: 'Back',
        defaultWeight: 50,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Pull-ups',
        equipmentType: 'other',
        category: 'Back',
        defaultWeight: 0,
        defaultSets: 3,
        defaultRepsMin: 6,
        defaultRepsMax: 10,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Dumbbell Row',
        equipmentType: 'other',
        category: 'Back',
        defaultWeight: 20,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2,
      },
      {
        name: 'T-Bar Row',
        equipmentType: 'plates',
        category: 'Back',
        defaultWeight: 40,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 10,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Face Pull',
        equipmentType: 'machine',
        category: 'Back',
        defaultWeight: 15,
        defaultSets: 3,
        defaultRepsMin: 12,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 2.5,
      },
    ],
  },
  {
    name: 'Shoulders',
    exercises: [
      {
        name: 'Overhead Press',
        equipmentType: 'plates',
        category: 'Shoulders',
        defaultWeight: 40,
        defaultSets: 3,
        defaultRepsMin: 6,
        defaultRepsMax: 8,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Dumbbell Shoulder Press',
        equipmentType: 'other',
        category: 'Shoulders',
        defaultWeight: 14,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2,
      },
      {
        name: 'Lateral Raise',
        equipmentType: 'other',
        category: 'Shoulders',
        defaultWeight: 8,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 1,
      },
      {
        name: 'Front Raise',
        equipmentType: 'other',
        category: 'Shoulders',
        defaultWeight: 8,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 1,
      },
      {
        name: 'Reverse Fly',
        equipmentType: 'other',
        category: 'Shoulders',
        defaultWeight: 6,
        defaultSets: 3,
        defaultRepsMin: 12,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 1,
      },
      {
        name: 'Arnold Press',
        equipmentType: 'other',
        category: 'Shoulders',
        defaultWeight: 12,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2,
      },
      {
        name: 'Shoulder Press Machine',
        equipmentType: 'machine',
        category: 'Shoulders',
        defaultWeight: 30,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 5,
      },
    ],
  },
  {
    name: 'Arms',
    exercises: [
      {
        name: 'Barbell Curl',
        equipmentType: 'plates',
        category: 'Arms',
        defaultWeight: 25,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Dumbbell Curl',
        equipmentType: 'other',
        category: 'Arms',
        defaultWeight: 10,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2,
      },
      {
        name: 'Hammer Curl',
        equipmentType: 'other',
        category: 'Arms',
        defaultWeight: 10,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2,
      },
      {
        name: 'Cable Curl',
        equipmentType: 'machine',
        category: 'Arms',
        defaultWeight: 20,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Tricep Pushdown',
        equipmentType: 'machine',
        category: 'Arms',
        defaultWeight: 25,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Skull Crusher',
        equipmentType: 'plates',
        category: 'Arms',
        defaultWeight: 20,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Overhead Tricep Extension',
        equipmentType: 'other',
        category: 'Arms',
        defaultWeight: 12,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 2,
      },
      {
        name: 'Close Grip Bench Press',
        equipmentType: 'plates',
        category: 'Arms',
        defaultWeight: 50,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 10,
        defaultProgressionIncrement: 2.5,
      },
    ],
  },
  {
    name: 'Legs',
    exercises: [
      {
        name: 'Squat',
        equipmentType: 'plates',
        category: 'Legs',
        defaultWeight: 60,
        defaultSets: 3,
        defaultRepsMin: 6,
        defaultRepsMax: 8,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Front Squat',
        equipmentType: 'plates',
        category: 'Legs',
        defaultWeight: 50,
        defaultSets: 3,
        defaultRepsMin: 6,
        defaultRepsMax: 8,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Leg Press',
        equipmentType: 'machine',
        category: 'Legs',
        defaultWeight: 100,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 5,
      },
      {
        name: 'Romanian Deadlift',
        equipmentType: 'plates',
        category: 'Legs',
        defaultWeight: 60,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 10,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Leg Curl',
        equipmentType: 'machine',
        category: 'Legs',
        defaultWeight: 35,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Leg Extension',
        equipmentType: 'machine',
        category: 'Legs',
        defaultWeight: 40,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Lunges',
        equipmentType: 'other',
        category: 'Legs',
        defaultWeight: 0,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Bulgarian Split Squat',
        equipmentType: 'other',
        category: 'Legs',
        defaultWeight: 0,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Hip Thrust',
        equipmentType: 'plates',
        category: 'Legs',
        defaultWeight: 60,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 5,
      },
      {
        name: 'Calf Raise',
        equipmentType: 'machine',
        category: 'Legs',
        defaultWeight: 50,
        defaultSets: 3,
        defaultRepsMin: 12,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 5,
      },
    ],
  },
  {
    name: 'Core',
    exercises: [
      {
        name: 'Plank',
        equipmentType: 'other',
        category: 'Core',
        defaultWeight: 0,
        defaultSets: 3,
        defaultRepsMin: 30,
        defaultRepsMax: 60,
        defaultProgressionIncrement: 0,
      },
      {
        name: 'Hanging Leg Raise',
        equipmentType: 'other',
        category: 'Core',
        defaultWeight: 0,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 0,
      },
      {
        name: 'Cable Crunch',
        equipmentType: 'machine',
        category: 'Core',
        defaultWeight: 30,
        defaultSets: 3,
        defaultRepsMin: 12,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 5,
      },
      {
        name: 'Ab Wheel Rollout',
        equipmentType: 'other',
        category: 'Core',
        defaultWeight: 0,
        defaultSets: 3,
        defaultRepsMin: 8,
        defaultRepsMax: 12,
        defaultProgressionIncrement: 0,
      },
      {
        name: 'Russian Twist',
        equipmentType: 'other',
        category: 'Core',
        defaultWeight: 5,
        defaultSets: 3,
        defaultRepsMin: 15,
        defaultRepsMax: 20,
        defaultProgressionIncrement: 2.5,
      },
      {
        name: 'Dead Bug',
        equipmentType: 'other',
        category: 'Core',
        defaultWeight: 0,
        defaultSets: 3,
        defaultRepsMin: 10,
        defaultRepsMax: 15,
        defaultProgressionIncrement: 0,
      },
    ],
  },
];

// Flatten all exercises for search
export const ALL_EXERCISES: ExerciseTemplate[] = EXERCISE_LIBRARY.flatMap(
  (category) => category.exercises
);

// Search exercises by name (case-insensitive)
export function searchExercises(query: string): ExerciseTemplate[] {
  if (!query.trim()) {
    return ALL_EXERCISES;
  }
  const lowerQuery = query.toLowerCase();
  return ALL_EXERCISES.filter((exercise) =>
    exercise.name.toLowerCase().includes(lowerQuery)
  );
}

// Get exercises by category
export function getExercisesByCategory(categoryName: string): ExerciseTemplate[] {
  const category = EXERCISE_LIBRARY.find(
    (cat) => cat.name.toLowerCase() === categoryName.toLowerCase()
  );
  return category?.exercises ?? [];
}
